name: distribute
run-name: Distributing
on:
  workflow_dispatch:

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: RedSockActions/distribute@v0.0.5
        with:
          target_repos: ${{ secrets.DISTRIBUTION_URLS }}
